targets:
  $default:
    builders:
      graphql_codegen:
        options:
          clients:
            - graphql
            - graphql_flutter
          scalars:
            Upload:
              type: MultipartFile
              import: package:http/http.dart
